### ISSUE TITLE
angular should be required for npm package

### ISSUE THREAD

**Issue by XVincentX** [BarakChamo/ng-promise-status#3]
Hello and at first thank you for this useful package.

When installing this lib using npm, it will not work because angularjs is installed as a module as well. For this reason, you should require it using `var angular = require('angular')` and not relying on the thing that the angular is a global object.

Usually the best way to deal with this is to have two files, one for `package.json` with module-style requiring and another one for `bower.json`

**Comment by BarakChamo** [comment]
Hey @XVincentX 

Thanks for bringing this up, I'll split the packages up and push a fix.

**Comment by XVincentX** [comment]
That would be definitely great.

**Comment by BarakChamo** [comment]
Hey @XVincentX 

The package is now updated with better support for module loading.
It's tested on both bower and npm loading with the current demo and the [browserify boilerplate](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate).

**Comment by XVincentX** [comment]
Great, I will have a look as soon as possible.

**Comment by XVincentX** [comment]
Working as expected. Great.
